<div class="section-example-container">
<pre class="python">
# Name Version
</pre><pre class="csharp">
# Name                               Version
Accord                               3.6.0
Accord.Fuzzy                         3.6.0
Accord.MachineLearning               3.6.0
Accord.Math                          3.6.0
Accord.Statistics                    3.6.0
CloneExtensions                      1.3.0
Common.Logging                       3.4.1
Common.Logging.Core                  3.4.1
CsvHelper                            19.0.0
Deedle                               2.1.0
DotNetZip                            1.16.0
DynamicInterop                       0.9.1
fasterflect                          3.0.0
MathNet.Numerics                     5.0.0
McMaster.Extensions.CommandLineUtils 2.6.0
Microsoft.IO.RecyclableMemoryStream  2.3.2
Microsoft.NET.Test.Sdk               16.9.4
Microsoft.TestPlatform.ObjectModel   16.9.4
Moq                                  4.16.1
NetMQ                                4.0.1.6
Newtonsoft.Json                      13.0.2
NodaTime                             3.0.5
NUnit                                3.13.3
NUnit3TestAdapter                    4.2.1
protobuf-net                         3.1.33
QLNet                                1.13.0
QuantConnect.pythonnet               2.0.39
RestSharp                            106.12.0
SharpZipLib                          1.3.3
System.ComponentModel.Composition    6.0.0
<? if ($cloudPlatform) { ?>
Accord.Audio                         3.6.0
Accord.Genetic                       3.6.0
Accord.MachineLearning.GPL           3.6.0
Catalyst                             1.0.39645
Catalyst.Models.English              1.0.30952
CNTK.CPUOnly                         2.8.0-rc0.dev20200201
Google.OrTools                       9.6.2534
LibTopoART                           0.97.0
MathNet.Filtering                    0.7.0
MathNet.Filtering.Kalman             0.7.0
MathNet.Spatial                      0.6.0
Microsoft.Data.Analysis              0.20.1
Microsoft.ML                         2.0.1
Microsoft.ML.CpuMath                 2.0.1
Microsoft.ML.DataView                2.0.1
Microsoft.ML.Ensemble                0.20.1
Microsoft.ML.FastTree                2.0.1
Microsoft.ML.LightGbm                2.0.1
Microsoft.ML.Mkl.Components          2.0.1
Microsoft.ML.OnnxRuntime             1.15.1
Microsoft.ML.TensorFlow              2.0.1
Microsoft.ML.TimeSeries              2.0.1
NumSharp                             0.30.0
OpenAI                               1.7.2
Plotly.NET                           3.0.1
Plotly.NET.Interactive               3.0.2
R.NET                                1.9.0
SharpLearning.AdaBoost               0.31.8
SharpLearning.Common.Interfaces      0.31.8
SharpLearning.Containers             0.31.8
SharpLearning.CrossValidation        0.31.8
SharpLearning.DecisionTrees          0.31.8
SharpLearning.Ensemble               0.31.8
SharpLearning.FeatureTransformations 0.31.8
SharpLearning.GradientBoost          0.31.8
SharpLearning.InputOutput            0.31.8
SharpLearning.Metrics                0.31.8
SharpLearning.Neural                 0.31.8
SharpLearning.Optimization           0.31.8
SharpLearning.RandomForest           0.31.8
SharpLearning.XGBoost                0.31.8
SharpNeatLib                         2.4.4
TensorFlow.Keras                     0.11.2
TensorFlow.NET                       0.110.2
<? } ?>
</pre></div>